# Generated by Django 4.0 on 2021-12-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.CharField(default='.', max_length=100),
        ),
    ]
