# Generated by Django 4.0 on 2021-12-21 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_dish_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFormRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.RegexValidator(message='Phone is format xxx xxx xxxx', regex='^(/d{3}[- .]?){2}/d{4}$')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('count_of_people', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, max_length=150)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date', '-time'),
            },
        ),
    ]
