# Generated by Django 4.0 on 2021-12-22 08:06

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_modelformregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to=base_app.models.HeroSection.get_file_name)),
            ],
        ),
    ]
