# Generated by Django 4.0 on 2021-12-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_aboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='desc_2',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='desc_3',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='feature_2',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='feature_3',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
