# Generated by Django 4.0 on 2021-12-22 08:57

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_aboutsection_desc_2_alter_aboutsection_desc_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(default='', upload_to=base_app.models.AboutSection.get_file_name),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
