# Generated by Django 4.0 on 2021-12-23 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_aboutsection_image_aboutsection_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelformregistration',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone is format xxx xxx xxxx', regex='^(/d{3}[- .]?){2}/d{4}$')]),
        ),
    ]
