# Generated by Django 4.0 on 2021-12-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_alter_modelformregistration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFormMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
