# Generated by Django 4.0 on 2021-12-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_modelformmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelformmessage',
            options={'ordering': ('-id',)},
        ),
    ]
