# Generated by Django 4.0 on 2021-12-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_alter_modelformmessage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='link',
        ),
    ]
