# Generated by Django 4.0 on 2021-12-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_remove_aboutsection_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
