# Generated by Django 4.0 on 2021-12-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_aboutsection_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelformmessage',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
