# Generated by Django 4.0 on 2021-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_modelformmessage_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelformregistration',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
